# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec7c7f4e78b75f9a0f75afd42d28660a4193bf49b96e19875caed713464e0e77b8c9eba79e3c638ccf77429134e61ec3105a0cd8c1c0c9e9841e62b007ec25ec
  facebook:
      app_id: 828115950641942
      app_secret: f79305c9871fc28573c9a53c8bb335d4

test:
  secret_key_base: cfb8bd73b2ac81dde023e1d4eca5807d16cf12a0106157755b23b1d25094d8f10271362488d3be93616c1c643a699a919a6ee9442510379fc0c40bad14267646
  facebook:
      app_id: 828115950641942
      app_secret: f79305c9871fc28573c9a53c8bb335d4
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook:
      app_id: <%= ENV["FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
